{% set name = "tomophantom" %}
{% set version = environ.get('GIT_DESCRIBE_TAG', '') %}
{% set python_min = "3.10" %}

package:
  name: {{ name }}-split
  version: {{ version }}

source:
  git_url: ../

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}

outputs:
  - name: {{ 'lib' + name }}
    script: build-lib.sh  # [unix]
    script: bld-lib.bat  # [win]
    build:
      script_env:
        - TOMOPHANTOM_VERSION={{ PKG_VERSION }}
      run_exports:
        - {{ pin_subpackage('lib' + name, max_pin='x.x') }}

    requirements:
      build:
        - {{ compiler('cxx') }}
        - cmake
        - ninja
      host:
        - libgomp      # [linux]
        - llvm-openmp  # [osx]

  - name: {{ name }}
    script: build-python.sh
    build:
      noarch: python
    requirements:
      build:
        - python {{ python_min }}
        - pip
        - setuptools
        - setuptools-git-versioning
      run:
        - {{ pin_subpackage('lib' + name) }}
        - python >={{ python_min }}
        - numpy
        - scipy
        - pillow
        - scikit-image
    test:
      files:
        - tomophantom/phantomlib/*
      requires:
        - python {{ python_min }}
        - pip
        - pytest
      imports:
        - tomophantom
      source_files:
        - tests/*
      commands:
        - pip check
        - pytest tests -vs

about:
  home: https://github.com/dkazanc/TomoPhantom
  license_file: LICENSE
  license:  Apache 2.0 license
  summary: 'Tomography Phantom Data generator'
