#creates pairs of versions using zip_keys, lists must be the same length
python:
  - 3.8
  - 3.9
  - 3.10 
  - 3.8
  - 3.9
  - 3.10 
  - 3.8
  - 3.9
  - 3.10 
  - 3.11
  - 3.8
  - 3.9
  - 3.10 
  - 3.11
numpy:
  - 1.21
  - 1.21
  - 1.21
  - 1.22
  - 1.22
  - 1.22
  - 1.23
  - 1.23
  - 1.23
  - 1.23
  - 1.24
  - 1.24
  - 1.24
  - 1.24
zip_keys:
  - python
  - numpy
