python:
  - 3.6
  - 3.7
  - 3.8
  - 3.9  
numpy:
  - 1.15 # [py=3.6]
  - 1.17 # [py>=3.5 and py<=3.7]
  - 1.18 # [py>=3.5 and py<=3.8]
  - 1.19 # [py>=3.6 and py<=3.8]
  - 1.20 # [py>=3.7 and py<=3.9]
