python:
  - 3.6 # only with np115
  - 3.7
  - 3.8
  - 3.9  
numpy:
  - 1.15 # [py==36]
  - 1.17 # [py>=35 and py<=37]
  - 1.18 # [py>=35 and py<=38]
  - 1.19 # [py>=36 and py<=38]
  - 1.20 # [py>=37 and py<=39]
