package:
  name: tomophantom
  version: {{ environ.get('CIL_VERSION', '') }}

build:
  preserve_egg_dir: False
  number: 0
  script_env:
    - CIL_VERSION

requirements:
  build:
    - python
    - numpy {{ numpy }}
    - setuptools
    - cython
    - cmake
    - blas=*=openblas # [not win]

  run:
    - {{ pin_compatible('numpy', min_pin='x.x', max_pin='x.x') }}
    - python
    - vc 14 # [win]
    - libgcc-ng # [unix]

about:
  home: https://github.com/dkazanc/TomoPhantom
  license:  Apache 2.0 license
  summary: 'Tomography Phantom Data generator'
