name: conda
on:
  push:
    branches: [master]
    tags: [v*]
  pull_request:
    branches: [master]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # use oldest ubuntu/macos images for max glibc compat:
        # https://stackoverflow.com/q/70019660
        os: [ubuntu-22.04, windows-latest, macos-14, macos-15-intel]
    steps:
      - uses: actions/checkout@v6
        with: {fetch-depth: 0}
      - if: startsWith(matrix.os, 'windows')
        uses: ilammy/msvc-dev-cmd@v1
      - uses: prefix-dev/rattler-build-action@v0.2.37
        with:
          recipe-path: recipe.yaml
          build-args: --experimental
          artifact-name: package-${{ matrix.os }}
      - if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
        name: conda upload -c httomo
        run: |
          rattler-build upload anaconda -o httomo -f ./output/*/lib*.conda     # library
          if [[ ${{ matrix.os }} =~ ubuntu* ]] ; then
            rattler-build upload anaconda -o httomo -f ./output/noarch/*.conda # noarch: python
          fi
        shell: bash
        env:
          ANACONDA_API_KEY: ${{ secrets.HTTOMO_TOKEN_27 }}
